version: '3.8'

services:
  app:
    build: .
    container_name: pchelnikova_asgi
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app:ServerApp --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    restart: always
