version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: online_store
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pchelnikova_cart
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      sh -c "
      until pg_isready -h db -p 5432; do
        echo 'Waiting for Postgres...'
        sleep 2
      done &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
