name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run unit tests
        run: |
          pytest -m "not api"

      - name: Set up Docker Compose for API tests
        run: docker compose up -d

      - name: Wait for the app to be ready
        run: |
          until curl --silent http://localhost:8000/; do
            echo "Waiting for app to be ready..."
            sleep 2
          done

      - name: Run API tests
        run: |
          pytest -m "api"

      - name: Tear down Docker Compose
        run: docker compose down
